yugioh:
  api:
    url: "https://db.ygoprodeck.com/api/v7/cardinfo.php?misc=yes"
  jwt:
    secret: "bWFfc2VjcmV0X3Rlc3RfMTIzNDU2Nzg5MDEyMw=="  # équivalent Base64
    expiration: 3600000
spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:sqlserver://MSI;databaseName=yugioh;encrypt=false;sendStringParametersAsUnicode=true
    username: Lola
    password: test12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          batch_size: 1000
        order_inserts: false
        order_updates: false
