yugioh:
  api:
    url: "https://db.ygoprodeck.com/api/v7/cardinfo.php?"
spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:sqlserver://MSI;databaseName=yugioh;encrypt=false;sendStringParametersAsUnicode=true
    username: Lola
    password: test1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          batch_size: 500
        order_inserts: false
        order_updates: false